build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - echo username=$$DOCKER_USERNAME
    - buildDate="b$DRONE_BUILD_NUMBER`date -u '+ %Y%m%d %H%M%S'`"
    - go get
    - go build -ldflags="-s -w -X main.buildDate '$buildDate'"

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-bintray
    when:
      branch: master

plugin:
  name: drone-bintray
  desc: Upload one or more artifacts to Bintray on build completion.
  type: publish
  image: plugins/drone-bintray
  labels:
    - publish
    - bintray
    - artifacts
