FROM plugins/base:i386

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone Bintray" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

ADD release/linux/i386/drone-bintray /bin/
ENTRYPOINT ["/bin/drone-bintray"]
